<?php
use Phalcon\Tag;
echo $this->getContent();
?>

<div class="container">
    <form action="apli" method="post">
        <div class="form-group">
            <label for="fieldcomment" class="col-sm-2 control-label">comment</label>
            <div class="col-sm-10">
            <?php echo $this->tag->textField(["comment","cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldcomment"]) ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <?php echo $this->tag->submitButton(["toko", "class" => "btn btn-default"]) ?>
            </div>
        </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>name</th>
                <th>image</th>
                <th>comment</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($kezi as $keziban): ?>
                    <tr>
                        <td><?php echo $keziban->name ?></td>
                        <td><img src="<?php echo $keziban->image ?>"</td>
                        <td><?php
                        $replacement = '<a href="\1" target="_blank">\1</a>';
                        $pattern = '(https?://[-_.!~*\'()a-zA-Z0-9;/?:@&=+$,%#]+)';
                        $text = mb_ereg_replace($pattern, $replacement, htmlspecialchars($keziban->comment));
                        echo $text;
                        ?></td>
                    </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</form>
<?= $this->tag->linkTo("profile", "profile"); ?>
<?= $this->tag->linkTo("logout", "logout"); ?>