<?= $this->tag->linkTo("/apli", "aplication\n"); ?>

<?php

$connection = $this->view->connection;
$connection->get("account/verify_credentials");
//var_dump($connection->get("account/verify_credentials"));

$info = $connection->get('account/verify_credentials');

print $info->id;
print $info->name;
echo "\n";
var_dump($connection->get("account/verify_credentials"));
?>

<?= $this->tag->linkTo("/apli", "aplication"); ?>
