

<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["apli", "Back"]) ?></li>
        </ul>
    </nav>
</div>
<div class="page-header">
    <h1>
        Edit profile
    </h1>
</div>

<?php echo $this->view->id; ?>
<?php echo $this->view->name; ?>
<img src="<?php echo $this->view->image ?>"
<?php echo $this->view->zikosyokai; ?>

<?php echo $this->getContent(); ?>
<p></p>
<?php
    echo $this->tag->form(
        [
            "profile",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data"
        ]
    );
?>

<div class="form-group">
    <label for="fieldImage" class="col-sm-2 control-label">Image</label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(["image","class" => "form-control", "id" => "fieldimage"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["henko", "class" => "btn btn-default"]) ?>
    </div>
</div>
<?php echo $this->tag->endForm(); ?>
</form>
</div>